# this is the build file for project autumnbot
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

MXX=/usr/bin/gcc
RC=/usr/bin/rustc
AS=/usr/bin/gcc
MM=/usr/bin/gcc
CU=/usr/bin/clang
CC=/usr/bin/gcc
CXX=/usr/bin/gcc

LD=/usr/bin/g++
RCLD=/usr/bin/rustc
SH=/usr/bin/g++
RCSH=/usr/bin/rustc
AR=/usr/bin/ar
RCAR=/usr/bin/rustc

autumnbot_LD=/usr/bin/clang++
autumnbot_CXX=/usr/bin/clang
autumnbot_CXX=/usr/bin/clang

autumnbot_CXXFLAGS=
autumnbot_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++20 -Isrc -isystem /home/muqiu/.xmake/packages/s/spdlog/v1.14.1/469f312ffeff47d9aa249e3ed8e400dc/include -isystem /home/muqiu/.xmake/packages/n/nlohmann_json/v3.11.3/ec1183311a224b34b5c138edda96fdde/include -stdlib=libc++ -DNDEBUG
autumnbot_LDFLAGS=-m64 -s -lpthread -lc++

default:  autumnbot

all:  autumnbot

.PHONY: default all  autumnbot

autumnbot: build/linux/x86_64/release/autumnbot
build/linux/x86_64/release/autumnbot: build/.objs/autumnbot/linux/x86_64/release/src/main.cpp.o build/.objs/autumnbot/linux/x86_64/release/src/plugins/plugins.cpp.o build/.objs/autumnbot/linux/x86_64/release/src/plugins/logger/logger.cpp.o build/.objs/autumnbot/linux/x86_64/release/src/errors/errors.cpp.o
	@echo linking.release autumnbot
	@mkdir -p build/linux/x86_64/release
	$(VV)$(autumnbot_LD) -o build/linux/x86_64/release/autumnbot build/.objs/autumnbot/linux/x86_64/release/src/main.cpp.o build/.objs/autumnbot/linux/x86_64/release/src/plugins/plugins.cpp.o build/.objs/autumnbot/linux/x86_64/release/src/plugins/logger/logger.cpp.o build/.objs/autumnbot/linux/x86_64/release/src/errors/errors.cpp.o $(autumnbot_LDFLAGS)

build/.objs/autumnbot/linux/x86_64/release/src/main.cpp.o: src/main.cpp
	@echo compiling.release src/main.cpp
	@mkdir -p build/.objs/autumnbot/linux/x86_64/release/src
	$(VV)$(autumnbot_CXX) -c $(autumnbot_CXXFLAGS) -o build/.objs/autumnbot/linux/x86_64/release/src/main.cpp.o src/main.cpp

build/.objs/autumnbot/linux/x86_64/release/src/plugins/plugins.cpp.o: src/plugins/plugins.cpp
	@echo compiling.release src/plugins/plugins.cpp
	@mkdir -p build/.objs/autumnbot/linux/x86_64/release/src/plugins
	$(VV)$(autumnbot_CXX) -c $(autumnbot_CXXFLAGS) -o build/.objs/autumnbot/linux/x86_64/release/src/plugins/plugins.cpp.o src/plugins/plugins.cpp

build/.objs/autumnbot/linux/x86_64/release/src/plugins/logger/logger.cpp.o: src/plugins/logger/logger.cpp
	@echo compiling.release src/plugins/logger/logger.cpp
	@mkdir -p build/.objs/autumnbot/linux/x86_64/release/src/plugins/logger
	$(VV)$(autumnbot_CXX) -c $(autumnbot_CXXFLAGS) -o build/.objs/autumnbot/linux/x86_64/release/src/plugins/logger/logger.cpp.o src/plugins/logger/logger.cpp

build/.objs/autumnbot/linux/x86_64/release/src/errors/errors.cpp.o: src/errors/errors.cpp
	@echo compiling.release src/errors/errors.cpp
	@mkdir -p build/.objs/autumnbot/linux/x86_64/release/src/errors
	$(VV)$(autumnbot_CXX) -c $(autumnbot_CXXFLAGS) -o build/.objs/autumnbot/linux/x86_64/release/src/errors/errors.cpp.o src/errors/errors.cpp

clean:  clean_autumnbot

clean_autumnbot: 
	@rm -rf build/linux/x86_64/release/autumnbot
	@rm -rf build/linux/x86_64/release/autumnbot.sym
	@rm -rf build/.objs/autumnbot/linux/x86_64/release/src/main.cpp.o
	@rm -rf build/.objs/autumnbot/linux/x86_64/release/src/plugins/plugins.cpp.o
	@rm -rf build/.objs/autumnbot/linux/x86_64/release/src/plugins/logger/logger.cpp.o
	@rm -rf build/.objs/autumnbot/linux/x86_64/release/src/errors/errors.cpp.o

